name: Trigger Repo Update

on:
  release:
    types: [published, unpublished, created, edited, deleted]
  repository_dispatch:
    types:
      - trigger-repo-update
  workflow_dispatch: 

env:
  triggerUpdate: ${{ false }}
  repoOwner: "JustSleightly"
  repoName: "VPM-Package-Listing-Template"
  repoBranch: "main"
  workflowName: "build-listing.yml"
  accessToken: ${{ secrets.VPM_TOKEN }}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo Update
        if: ${{ env.triggerUpdate == 'true' }}
        uses: actions/github-script@v6
        with: 
          github-token: ${{ env.accessToken }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ env.repoOwner }}',
              repo: '${{ env.repoName }}',
              workflow_id: '${{ env.workflowName }}',
              ref: '${{ env.repoBranch }}',
            })

# thanks to bd_, modified from this action: https://github.com/bdunderscore/modular-avatar/blob/main/.github/workflows/trigger-repo-rebuild.yml
